---
# tasks file for nodejs

- name: "Install nodejs"
  tags: "nodejs"
  ansible.builtin.apt:
    name:
    - nodejs
    - postgresql-client-14
    state: present
    update_cache: true

- name: "Install npm"
  tags: "nodejs"
  ansible.builtin.package:
    name: npm

- name: "Creates directory project"
  tags: "nodejs"
  ansible.builtin.file:
    path: /home/vagrant/nginx_server_project
    state: directory
    mode: '0755'

- name: "Copy config files"
  tags: "nodejs"
  ansible.builtin.template:
    src: templates/nodejs/webserver.j2
    dest: /home/vagrant/nginx_server_project/webserver.js
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: "Init npm"
  tags: "nodejs"
  ansible.builtin.shell: 'cd /home/vagrant/nginx_server_project && npm init -y && npm install pg && npm install express'
  args:
    executable: /bin/bash
  register: outputcode
  changed_when: outputcode.rc != 0

- name: "Create service file"
  tags: "nodejs"
  template:
    src: templates/nodejs/service
    dest: /etc/systemd/system/nodejs.service
  register: service_conf

- name: "Reload systemd daemon"
  tags: "nodejs"
  systemd:
    daemon_reload: yes
  when: service_conf.changed

- name: "Start NodeJS service"
  tags: "nodejs"
  service:
    name: nodejs
    state: started
    enabled: yes
