---
# tasks file for nginx_install

- name: "Install nginx"
  tags: "nginx"
  ansible.builtin.apt:
    name:
    - nginx
    state: present
    update_cache: true

- name: "Ensure nginx is enabled"
  tags: "nginx"
  ansible.builtin.systemd:
    name: nginx
    enabled: yes

- name: "Redirecting error logs on rsyslog"
  tags: "nginx"
  lineinfile:
    dest: '/etc/nginx/nginx.conf'
    regexp: 'error_log /var/log/nginx/error.log;'
    line: '        error_log syslog:server=192.168.255.250,tag=nginx_error;'

- name: "Redirecting access logs on rsyslog"
  tags: "nginx"
  lineinfile:
    dest: '/etc/nginx/nginx.conf'
    regexp: 'access_log /var/log/nginx/access.log;'
    line: '        access_log syslog:server=192.168.255.250,tag=nginx_access,facility=local6,severity=info;'


- name: "Copy config files"
  tags: "nginx"
  ansible.builtin.copy:
    src: templates/nginx/webserver.config
    dest: /etc/nginx/sites-available/web-monkey.ru.config
    owner: root
    group: root
    mode: '0644'
    follow: yes

- name: "Enabled config nginx"
  tags: "nginx"
  ansible.builtin.file:
    src: /etc/nginx/sites-available/web-monkey.ru.config
    dest: /etc/nginx/sites-enabled/web-monkey.ru.config
    owner: root
    group: root
    state: link

# - name: "Fetch files key"
#   tags: "cert"
#   fetch:
#     src: /etc/ssl/private/nginx-selfsigned.key
#     dest: templates/nginx/nginx-selfsigned.key
#     follow: yes

# - name: "Fetch files cert"
#   tags: "cert"
#   fetch:
#     src: /etc/ssl/certs/nginx-selfsigned.crt
#     dest: templates/nginx/nginx-selfsigned.crt
#     follow: yes

# - name: "Fetch files self-signed.conf"
#   tags: "cert"
#   fetch:
#     src: /etc/nginx/snippets/self-signed.conf
#     dest: templates/nginx/self-signed.conf
#     follow: yes

# - name: "Fetch files ssl-params.conf"
#   tags: "cert"
#   fetch:
#     src: /etc/nginx/snippets/ssl-params.conf
#     dest: templates/nginx/ssl-params.conf
#     follow: yes

# - name: "Fetch files ssl-params.conf"
#   tags: "cert"
#   fetch:
#     src: /etc/nginx/dhparam.pem
#     dest: templates/nginx/dhparam.pem
#     follow: yes

- name: "Copy files key"
  tags: "cert"
  copy:
    src: templates/nginx/certs/nginx-selfsigned.key
    dest: /etc/ssl/private/nginx-selfsigned.key
    owner: root
    group: root
    mode: '0600'
    follow: yes

- name: "Copy files cert"
  tags: "cert"
  copy:
    src: templates/nginx/certs/nginx-selfsigned.crt
    dest: /etc/ssl/certs/nginx-selfsigned.crt
    owner: root
    group: root
    mode: '0644'
    follow: yes

- name: "Copy files self-signed.conf"
  tags: "cert"
  copy:
    src: templates/nginx/certs/self-signed.conf
    dest: /etc/nginx/snippets/self-signed.conf
    owner: root
    group: root
    mode: '0600'
    follow: yes

- name: "Copy files ssl-params.conf"
  tags: "cert"
  copy:
    src: templates/nginx/certs/ssl-params.conf
    dest: /etc/nginx/snippets/ssl-params.conf
    owner: root
    group: root
    mode: '0644'
    follow: yes

- name: "Copy files dhparam.pem"
  tags: "cert"
  copy:
    src: templates/nginx/certs/dhparam.pem
    dest: /etc/nginx/dhparam.pem
    owner: root
    group: root
    mode: '0644'
    follow: yes

- name: "Restart nginx"
  tags: "nginx"
  ansible.builtin.service:
    name: nginx
    state: restarted