---

- name: "Install webserver"
  hosts: frontEnd
  become: true

  tasks:
  - name: "Install nginx"
    tags: "nginx"
    ansible.builtin.apt:
      name:
      - nginx
      state: present
      update_cache: true