---

- name: "Install tools"
  hosts: all
  become: true

  tasks:
    - name: Set timezone Moscow
      community.general.timezone:
        name: Europe/Moscow

    

- name: "Install webserver"
  hosts: frontServers
  become: true
  roles:
  - nginx_install

- name: "Install backEnd"
  hosts: backEndServers
  become: true
  roles:
  - nodejs

- name: "Install BDServers"
  hosts: BDServers
  become: true
  roles:
  - postgres_install
  - repmgr

- name: "Install barman"
  hosts: backupServers, BDServers
  become: true
  roles:
  - barman_install