---

- name: "Install webserver"
  hosts: frontServers
  become: true
  roles:
  - nginx_install

- name: "Install backEnd"
  hosts: backEndServers
  become: true
  roles:
  - nodejs

- name: "Install BDServers"
  hosts: BDServers
  become: true
  roles:
  - postgres_install
  - repmgr
  
- name: "Start webserver"
  hosts: backEndServers
  become: true

  tasks:
  - name: "Start server nodejs"
    tags: "nodejs"
    ansible.builtin.command: '/home/vagrant/nginx_server_project/start_server.sh'
    register: start_server
    changed_when: start_server.rc != 0