---
# tasks file for rsyslog

- name: "Copy config file rsyslog.conf"
  tags: nginx, backup, nodejs, postgres
  copy:
    src: templates/rsyslog/rsyslog.conf
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0644

- name: "Copy config file"
  tags: nginx, backup, nodejs, postgres
  copy:
    src: templates/rsyslog/remote_logs.conf
    dest: /etc/rsyslog.d/remote_logs.conf
    owner: root
    group: root
    mode: 0644

- name: "start rsyslog"
  service:
    name: rsyslog
    state: restarted
